version: "3.9"

services:
  db:
    container_name: db
    image: "mysql:8.0.19"
    hostname: mysql
    restart: always
    ports:
    - "33061:3306"
    command: "--default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql"
    volumes:
      - ./docs/sql/blog.sql:/data/application/init.sql
      - /var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
  go-gin-example:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      WAIT_TIMEOUT: 60
      WAIT_HOSTS: mysql:3306